services:
  - type: web
    name: learning-tracker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: POSTGRES_USER
        value: user
      - key: POSTGRES_PASSWORD
        value: password
      - key: POSTGRES_DB
        value: learning_tracker
      - key: POSTGRES_URL
        value: db
